
import os
from dataclasses import dataclass, field

@dataclass
class NexusConfig:
    # --- LLM Settings ---
    # Provider: 'ollama', 'llamacpp', 'openai', 'anthropic', 'groq', 'gemini'
    LLM_PROVIDER: str = "ollama" 
    
    # Ollama Specific
    OLLAMA_MODEL: str = "gpt-oss:20b-cloud"
    OLLAMA_BASE_URL: str = "http://localhost:11434/v1"
    
    # Llama.cpp Specific
    LLAMA_CPP_PATH: str = r"d:\Agent-S\models\your-model.gguf" 
    LLAMA_CPP_N_CTX: int = 4096
    LLAMA_CPP_N_GPU_LAYERS: int = -1  # -1 for all
    
    # OpenAI Specific
    OPENAI_API_KEY: str = os.environ.get("OPENAI_API_KEY", "")
    OPENAI_MODEL: str = "gpt-4o"
    OPENAI_BASE_URL: str = "https://api.openai.com/v1"
    
    # Anthropic Specific
    ANTHROPIC_API_KEY: str = os.environ.get("ANTHROPIC_API_KEY", "")
    ANTHROPIC_MODEL: str = "claude-sonnet-4-20250514"
    
    # Groq Specific
    GROQ_API_KEY: str = os.environ.get("GROQ_API_KEY", "")
    GROQ_MODEL: str = "llama-3.3-70b-versatile"
    GROQ_BASE_URL: str = "https://api.groq.com/openai/v1"
    
    # Gemini Specific
    GEMINI_API_KEY: str = os.environ.get("GEMINI_API_KEY", "")
    GEMINI_MODEL: str = "gemini-2.0-flash"
    GEMINI_BASE_URL: str = "https://generativelanguage.googleapis.com/v1beta/openai/"
    
    # --- Browser Settings ---
    BROWSER_CONTROL_URL: str = "http://127.0.0.1:18791"
    BROWSER_AUTH_TOKEN: str = ""  # Auto-generated by OpenClaw if empty
    BROWSER_PROFILE: str = "openclaw"
    BROWSER_CDP_PORT: int = 9222
    BROWSER_HEADLESS: bool = False
    BROWSER_LIVE_VIEW: bool = True   # Start visual rendering server
    BROWSER_LIVE_VIEW_PORT: int = 18900
    
    # --- Memory Settings ---
    MEMORY_DIR: str = ".nexus_memory"
    EMBEDDING_MODEL: str = "intfloat/e5-base-v2"
    SIMILARITY_THRESHOLD: float = 0.75
    
    # Context Retrieval
    MAX_CONTEXT_CHUNKS: int = 3
    
    # --- Shell Settings ---
    SHELL_TIMEOUT: int = 120
    SHELL_SHOW_UI: bool = False  # Set to True for visible window

# Global Config Instance
config = NexusConfig()
